name: Build C/C++ (CLI)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Requirements
      run: sudo apt-get update && sudo apt-get install qt6-tools-dev
    - name: Build
      run: make -j
